### ISSUE TITLE
Wire library do not have endTransmission(uint8) interface.

### ISSUE THREAD

**Issue by masato-ka** [Seeed-Studio/stm32f4ArduinoCore#7]
I think Wire library is compliant old Arduino library interface( <= 1.0.0)
Is the version 1.0.0 correct ?

I want to new version core library for WioLTE Cat 1 board.

**Comment by trawinlegacy** [comment]
I am having the same issue #8 . Can this please be fixed so that functionality with other I2C sensors can be done? 

When the endTransmission(false); is set to endTransmission(); instead, does not appear to read the device address correctly.
 I have been trying to configure the Adafruit breakout board of the MPL3115A2 sensor.

**Comment by trawinlegacy** [comment]
I adjusted the Wire.cpp to include the following:
`
uint8 TwoWire::endTransmission(uint8_t sendStop) {		// ******* originally - endTransmission(void) *******
	if (tx_buf_overflow) return EDATA;

	i2c_start(port);

	i2c_shift_out(port, (tx_addr << 1) | I2C_WRITE);
	if (!i2c_get_ack(port)) return ENACKADDR;

	// shift out the address we're transmitting to
	for (uint8 i = 0; i < tx_buf_idx; i++) {
		uint8 ret = writeOneByte(tx_buf[i]);
		if (ret) {
			//Serial1.println("endTransmission failed");
			return ret;    // SUCCESS is 0
		}
	}

	if (sendStop) {				// ******* originally - i2c_stop(port); with no if statement *******
		i2c_stop(port);
	}

	tx_buf_idx = 0;
	tx_buf_overflow = false;
	return SUCCESS;
}

//	This provides backwards compatibility with the original
//	definition, and expected behaviour, of endTransmission
//
uint8 TwoWire::endTransmission(void)			// ******* Originally function was not included *******
{
  return endTransmission(true);
}
`

I also adjusted the Wire.h to include the following
`
uint8 endTransmission(void);
    uint8 endTransmission(uint8_t);
`

This allows the code to run but it does not read the sensor properly as these are the results from the MPL3115A2 sensor connected:

-11.25*C
 
When it should be 22.5*C
